name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - uses: ddev/github-action-setup-ddev@v1

      - name: Install dependencies 👨🏻‍💻
        run: ddev yarn install

      - name: Run linter 👀
        run: yarn lint

      - name: Generate output ⚙️
        run: yarn generate

      - name: Run Playwright 🌎
        run: |
          npx playwright install
          BASE_URL=https://magento2-model-generator.test/ npx playwright test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Playwright report
          path: |
            playwright-report
