name: dependabot-auto-merge

on:
  pull_request:
    branches:
      - main

jobs:
  dependabot-auto-merge:
    runs-on: ${{ matrix.os }}

    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.dependabot_auto_merge }}
